#! /bin/sh

# usage: ./make_deamon <name> <path_to_deamon_progarm_folder> <deamon_program_name>

name=$1
path=$2
deamon=$3

outfile="$name"

echo "#!/bin/sh" > $outfile
echo "# This script was autogenerated by make_deamon.sh" >> $outfile
cat <<EOF >> $outfile 
NAME="$name"
DAEMON="$path/$name"
PIDFILE="$path/$name.pid"
DAEMON_OPTS=""
EOF
cat deamon_base.sh >> $outfile

